services:
  # 1. DATABASE
  aura.db:
    image: postgres:15-alpine
    container_name: aura.db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=zxc123456
      - POSTGRES_DB=aura_identity_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - aura-network

  # 2. IDENTITY SERVICE
  identity-service:
    container_name: identity-service
    build:
      context: ../
      dockerfile: backend/src/Services/Identity/AURA.Services.Identity.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=aura.db;Port=5432;Database=aura_identity_db;Username=admin;Password=zxc123456
    ports:
      - "5001:8080"
    depends_on:
      - aura.db
    networks:
      - aura-network

  # 3. MEDICAL RECORD SERVICE
  medical-record-service:
    container_name: medical-record-service
    build:
      context: ../
      dockerfile: backend/src/Services/MedicalRecord/AURA.Services.MedicalRecord.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=aura.db;Port=5432;Database=aura_medical_db;Username=admin;Password=zxc123456
    ports:
      - "5002:8080"
    depends_on:
      - aura.db
    networks:
      - aura-network

  # 4. IMAGING SERVICE
  imaging-service:
    container_name: imaging-service
    restart: always
    build:
      context: ../
      dockerfile: backend/src/Services/Imaging/AURA.Services.Imaging.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=aura.db;Port=5432;Database=aura_imaging_db;Username=admin;Password=zxc123456
    ports:
      - "5003:8080"
    volumes:
      - ./uploads_data:/app/uploads
    depends_on:
      - aura.db
      - rabbitmq
    networks:
      - aura-network

  # 5. BILLING SERVICE 
  billing-service:
    container_name: billing-service
    build:
      context: ../
      dockerfile: backend/src/Services/Billing/AURA.Services.Billing.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - aura-network

  # 6. NOTIFICATION SERVICE
  notification-service:
    container_name: notification-service
    build:
      context: ../
      dockerfile: backend/src/Services/Notification/AURA.Services.Notification.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__Host=rabbitmq
    ports:
      - "5005:8080"
    depends_on:
      - rabbitmq
    networks:
      - aura-network

  # 7. AI CORE SERVICE
  ai-core-service:
    container_name: ai-core-service
    restart: always
    build:
      context: ../backend/src/Services/AICore
      dockerfile: Dockerfile 
    ports:
      - "5006:8000"
    volumes:
      - ./uploads_data:/app/uploads
      - ./ai_static:/app/static/results
    networks:
      - aura-network

  # 8. API GATEWAY
  gateway:
    image: nginx:latest
    container_name: aura-gateway
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - identity-service
      - medical-record-service
      - imaging-service
      - billing-service
    networks:
      - aura-network

  # 9. RabbitMQ 
  rabbitmq:
    image: rabbitmq:3-management
    container_name: aura-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - aura-network

networks:
  aura-network:
    driver: bridge

volumes:
  postgres_data: